// SPDX-FileCopyrightText: 2024 Ed <96445749+TheShuEd@users.noreply.github.com>
// SPDX-FileCopyrightText: 2025 GabyChangelog <agentepanela2@gmail.com>
// SPDX-FileCopyrightText: 2025 Kyoth25f <kyoth25f@gmail.com>
//
// SPDX-License-Identifier: MIT

using Content.Client.Message;
using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Map;
using Robust.Shared.Utility;
using Content.Client.Pinpointer.UI;
using static Robust.Client.UserInterface.Controls.BoxContainer;
using Content.Shared._Gabystation.StationTeleporter;

namespace Content.Client._Gabystation.StationTeleporter;

[GenerateTypedNameReferences]
public sealed partial class StationTeleporterConsoleWindow : FancyWindow
{
    [Dependency] private readonly IEntityManager _entManager = default!;
    private readonly SpriteSystem _spriteSystem;
    private readonly SharedTransformSystem _xformSystem;

    public event Action<NetEntity?>? OnTeleporterSelected;

    private NetEntity? _trackedEntity;
    private Texture _teleportMarkerTexture;
    private Texture _selectedTeleportMarkerTexture;

    private readonly Color _linkedColor = new Color(18, 61, 82);
    private readonly Color _selectedColor = new Color(49, 117, 7);
    private readonly Color _baseColor = new Color(30, 30, 34);
    private readonly Color _borderColor = Color.Black;
    private readonly Color _poweredBlibColor = Color.Aqua;
    private readonly Color _unpoweredBlibColor = Color.Gray;
    private readonly Color _selectedBlibColor = Color.Green;

    public StationTeleporterConsoleWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _spriteSystem = _entManager.System<SpriteSystem>();
        _xformSystem = _entManager.System<SharedTransformSystem>();

        _teleportMarkerTexture = _spriteSystem.Frame0(new SpriteSpecifier.Texture(new ResPath("/Textures/Interface/NavMap/ring.png")));
        _selectedTeleportMarkerTexture = _spriteSystem.Frame0(new SpriteSpecifier.Texture(new ResPath("/Textures/Interface/NavMap/ring_filled.png")));

        NavMap.TrackedEntitySelectedAction += ClickTeleporterOnNavMap;
    }

    public void Set(StationTeleporterConsoleBoundUserInterface userInterface, string stationName, EntityUid? mapUid)
    {
        if (_entManager.TryGetComponent<TransformComponent>(mapUid, out var xform))
            NavMap.MapUid = xform.GridUid;
        else
            NavMap.Visible = false;

        StationName.AddStyleClass("LabelBig");
        StationName.Text = stationName;
        NavMap.ForceNavMapUpdate();
    }

    public void ShowTeleporters(StationTeleporterState state, EntityUid monitor, EntityCoordinates? monitorCoords)
    {
        ClearOutdatedData();

        var teleporters = state.Teleporters;

        //No teleporters
        if (teleporters.Count == 0)
        {
            NoTeleportersLabel.Visible = true;
            return;
        }

        NoTeleportersLabel.Visible = false;


        // Show all teleporters
        foreach (var teleporter in teleporters)
        {
            var coordinates = _entManager.GetCoordinates(teleporter.Coordinates);

            var isSelected = teleporter.TeleporterUid == state.SelectedTeleporter;
            var isLinked = teleporter.LinkCoordinates is not null;

            var bgColor = isLinked ? _linkedColor : _baseColor;
            if (isSelected)
                bgColor = _selectedColor;


            // Primary container to hold the button UI elements
            var panelContainer = new PanelContainer()
            {
                HorizontalAlignment = HAlignment.Center,
                VerticalAlignment = VAlignment.Center,
                HorizontalExpand = true,
                Margin = new Thickness(10),
                PanelOverride = new StyleBoxFlat
                {
                    BackgroundColor = bgColor,
                    BorderColor = _borderColor,
                    BorderThickness = new(2),
                },
            };

            TeleportersTable.AddChild(panelContainer);

            var mainBox = new BoxContainer()
            {
                Orientation = LayoutOrientation.Vertical,
                HorizontalExpand = true,
            };

            panelContainer.AddChild(mainBox);


            // Teleporter name
            var nameLabel = new RichTextLabel()
            {
                HorizontalExpand = true,
                HorizontalAlignment = HAlignment.Center,
                Margin = new Thickness(0, 5),
            };
            nameLabel.SetMarkup($"[bold]{teleporter.Name}[/bold]");

            mainBox.AddChild(nameLabel);


            //Left subpart
            var leftBox = new BoxContainer()
            {
                SetWidth = 30,
                Orientation = LayoutOrientation.Vertical,
                HorizontalExpand = true,
            };

            mainBox.AddChild(leftBox);


            //Right subpart
            var rightBox = new BoxContainer()
            {
                Orientation = LayoutOrientation.Vertical,
                HorizontalExpand = true,
            };

            mainBox.AddChild(rightBox);


            // Locating button
            var locateButton = new TeleporterButton()
            {
                Text = Loc.GetString("teleporter-console-user-interface-locate"),
                TeleporterUid = teleporter.TeleporterUid,
                Coordinates = coordinates,
                HorizontalAlignment = HAlignment.Right,
                SetWidth = 200f,
            };

            rightBox.AddChild(locateButton);

            var buttonLoc = "teleporter-console-user-interface-start-connection";
            if (!teleporter.Powered)
                buttonLoc = "teleporter-console-user-interface-no-power";
            else if (isLinked)
                buttonLoc = "teleporter-console-user-interface-cut-connection";

            var linkButton = new TeleporterButton()
            {
                Text = Loc.GetString(buttonLoc),
                TeleporterUid = teleporter.TeleporterUid,
                Coordinates = coordinates,
                HorizontalAlignment = HAlignment.Right,
                SetWidth = 200f,
                Disabled = !teleporter.Powered,
            };
            linkButton.OnButtonUp += _ => OnTeleporterSelected?.Invoke(teleporter.TeleporterUid);

            rightBox.AddChild(linkButton);

            var blipColor = _poweredBlibColor;
            if (isSelected)
                blipColor = _selectedBlibColor;
            else if (!teleporter.Powered)
                blipColor = _unpoweredBlibColor;

            if (coordinates != null && NavMap.Visible)
            {
                var blip = new NavMapBlip(
                    coordinates.Value,
                    isLinked ? _selectedTeleportMarkerTexture : _teleportMarkerTexture,
                    blipColor,
                    false);
                NavMap.TrackedEntities.TryAdd(teleporter.TeleporterUid, blip);

                locateButton.OnButtonUp += _ =>
                {
                    if (_trackedEntity == teleporter.TeleporterUid)
                        _trackedEntity = null;
                    else
                    {
                        _trackedEntity = teleporter.TeleporterUid;
                        NavMap.CenterToCoordinates(coordinates.Value);
                    }

                    UpdateTeleportersTable();
                };
            }

            //Add teleporters links lines
            if (teleporter.Coordinates is not null && teleporter.LinkCoordinates is not null)
            {
                var coordsOne = _entManager.GetCoordinates(teleporter.Coordinates);
                var coordsTwo = _entManager.GetCoordinates(teleporter.LinkCoordinates);

                if (coordsOne is null || coordsTwo is null)
                    continue;

                var mapId1 = _xformSystem.GetMapId(coordsOne.Value);
                var mapId2 = _xformSystem.GetMapId(coordsTwo.Value);

                if (mapId1 != mapId2
                    || mapId1 == MapId.Nullspace
                    || mapId2 == MapId.Nullspace)
                    continue;

                NavMap.LinkedTeleportersCoordinates.Add((
                    _xformSystem.ToMapCoordinates(coordsOne.Value).Position,
                    _xformSystem.ToMapCoordinates(coordsTwo.Value).Position));
            }
        }
    }

    private void ClickTeleporterOnNavMap(NetEntity? netEntity)
    {
        OnTeleporterSelected?.Invoke(netEntity);
    }

    private void ClearOutdatedData()
    {
        TeleportersTable.RemoveAllChildren();
        NavMap.TrackedCoordinates.Clear();
        NavMap.TrackedEntities.Clear();
        NavMap.LinkedTeleportersCoordinates.Clear();
    }

    private void UpdateTeleportersTable()
    {
        foreach (var teleporter in TeleportersTable.Children)
        {
            if (teleporter is not TeleporterButton castTeleporter
                || castTeleporter.Coordinates is null
                || !NavMap.TrackedEntities.TryGetValue(castTeleporter.TeleporterUid, out var data))
                continue;

            data = new NavMapBlip(data.Coordinates, data.Texture, _poweredBlibColor, false);
            NavMap.TrackedEntities[castTeleporter.TeleporterUid] = data;
        }
    }
}

public sealed class TeleporterButton : Button
{
    public int IndexInTable;
    public NetEntity TeleporterUid;
    public EntityCoordinates? Coordinates;
}
